name: Almeida

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check_tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Get tickets
        run: |
          for run in {1..120}; do
            RESPONSE=$(curl -s 'https://almeida.co.uk/admin/wp-admin/admin-ajax.php' --data-raw 'action=calendar&filters=event%3D8236')
            if echo "$RESPONSE" | grep -q 'Book Tickets'; then
              echo "The response contains 'Book Tickets'."
              echo "$RESPONSE" | grep 'Book Tickets'
              exit 111
            else
              echo "The response does not contain 'Book Tickets'."
            fi
            sleep 10
          done
          
