name: Almeida

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: almeida

jobs:
  check_tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Get tickets
        run: |
          for run in {1..120}; do
            RESPONSE=$(curl https://ticketing.almeida.co.uk/api/products/productionseasons --data 'productionSeasonIdFilter%5B%5D=7450&startDate=2024-01-15T00%3A00%3A00Z&endDate=2025-03-15T23%3A59%3A59Z')
          
            echo $RESPONSE
            
            MATCHES=$(echo $RESPONSE | jq '.[0].performances[] | select(.isOnSale != false or (.performanceStatusMessage != "Sold out" and .performanceStatusMessage != "Tickets not on sale"))')
            
            echo $MATCHES
            
            if [ -z "$MATCHES" ]
            then
            echo "No matches found"
            else
            echo "Matches found"
            exit 111
            fi
  
            sleep 10
          done
          
