name: Almeida

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check_tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Get tickets
        run: |
          RESPONSE=$(curl https://ticketing.almeida.co.uk/api/products/productionseasons --data 'productionSeasonIdFilter%5B%5D=5849&startDate=2023-01-15T00%3A00%3A00Z&endDate=2025-01-15T23%3A59%3A59Z')
          MATCHES=$($RESPONSE | jq '.[0].performances[] | select(.isOnSale != false or .performanceStatusMessage != "Sold out")')
          if [ -z "$MATCHES" ]
          then
          echo "No matches found"
          else
          echo "Matches found"
          exit 111
          fi
